### ISSUE TITLE
Force re-localization during repeat not supported by the path tracker

### ISSUE THREAD

**Issue by cheneyuwu** [utiasASRL/vtr3#108]
Force to metric-localization state during repeat does not work as expected (after recent cusp issue fix on path tracker side) - disable this function for now in the UI (see https://github.com/utiasASRL/vtr3_gui/blob/c657b3496993c14d6f0347b846881b5019b73dad/vtr-ui/src/components/goal/GoalCurrent.js#L122), re-enable after path tracker overhaul.

**Comment by a-krawciw** [comment]
Path tracker has changed.
