### ISSUE TITLE
Error in Colcon build —symlink-install

### ISSUE THREAD

**Issue by rishabhramteke** [utiasASRL/vtr3#138]
i am getting this error when doing colcon build —symlink-install in ~/ASRL/vtr3/main
Please help

colcon build --symlink-install
Starting >>> lgmath  
Starting >>> vtr_messages
Starting >>> vtr_logging
Starting >>> cudpp
Starting >>> vtr_documentation
Starting >>> vtr_ui
/home/rishabh/.local/lib/python3.8/site-packages/setuptools/dist.py:772: UserWarning: Usage of dash-separated 'script-dir' will not be supported in future versions. Please use the underscore name 'script_dir' instead
  warnings.warn(
/home/rishabh/.local/lib/python3.8/site-packages/setuptools/dist.py:772: UserWarning: Usage of dash-separated 'install-scripts' will not be supported in future versions. Please use the underscore name 'install_scripts' instead
  warnings.warn(
Finished <<< cudpp [1.40s]                                      
Starting >>> gpusurf
Finished <<< vtr_logging [1.46s]
Finished <<< lgmath [1.58s]                                  
Starting >>> steam
Finished <<< gpusurf [0.45s]                                          
Finished <<< steam [1.00s]                                            
Starting >>> vtr_steam_extensions
Finished <<< vtr_steam_extensions [0.34s]                              
--- stderr: vtr_ui                                                    
/home/rishabh/.local/lib/python3.8/site-packages/setuptools/dist.py:772: UserWarning: Usage of dash-separated 'script-dir' will not be supported in future versions. Please use the underscore name 'script_dir' instead
  warnings.warn(
/home/rishabh/.local/lib/python3.8/site-packages/setuptools/dist.py:772: UserWarning: Usage of dash-separated 'install-scripts' will not be supported in future versions. Please use the underscore name 'install_scripts' instead
  warnings.warn(
/home/rishabh/.local/lib/python3.8/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/home/rishabh/.local/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/home/rishabh/.local/lib/python3.8/site-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: 1.13.1-unknown is an invalid version and will not be supported in a future release
  warnings.warn(
/home/rishabh/.local/lib/python3.8/site-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: 0.1.36ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
/home/rishabh/.local/lib/python3.8/site-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: 0.23ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
---
Finished <<< vtr_ui [5.90s]
Finished <<< vtr_messages [6.68s]                                  
Starting >>> vtr_common
Starting >>> vtr_storage
Starting >>> vtr_lgmath_extensions
Finished <<< vtr_lgmath_extensions [0.30s]                                  
Finished <<< vtr_common [0.39s]                                          
Starting >>> vtr_safety_monitor
Finished <<< vtr_storage [0.73s]                                          
Starting >>> vtr_pose_graph
Finished <<< vtr_safety_monitor [0.49s]                                  
Finished <<< vtr_pose_graph [0.97s]                                      
Starting >>> vtr_path_planning
Starting >>> vtr_path_tracker                                            
Finished <<< vtr_path_planning [0.40s]                                    
Starting >>> vtr_mission_planning
Finished <<< vtr_path_tracker [0.56s]                                    
Finished <<< vtr_documentation [9.40s]                                    
Finished <<< vtr_mission_planning [0.72s]
Starting >>> vtr_tactic
Finished <<< vtr_tactic [0.47s]                        
Starting >>> vtr_lidar
Starting >>> vtr_vision
Finished <<< vtr_lidar [0.71s]                                            
--- stderr: vtr_vision                                
/home/rishabh/ASRL/vtr3/main/src/vtr_vision/src/modules/matching/mel_matcher_module.cpp: In member function ‘void vtr::vision::MelMatcherModule::matchChannelGPU(vtr::vision::CameraQueryCache&, const vtr::vision::LandmarkId&, const ChannelLandmarks&)’:
/home/rishabh/ASRL/vtr3/main/src/vtr_vision/src/modules/matching/mel_matcher_module.cpp:362:37: error: ‘const struct vtr::vision::Features’ has no member named ‘gpu_descriptors’; did you mean ‘descriptors’?
  362 |     if (query_channel_lm.appearance.gpu_descriptors.empty()) {
      |                                     ^~~~~~~~~~~~~~~
      |                                     descriptors
/home/rishabh/ASRL/vtr3/main/src/vtr_vision/src/modules/matching/mel_matcher_module.cpp:367:47: error: ‘const struct vtr::vision::Features’ has no member named ‘gpu_descriptors’; did you mean ‘descriptors’?
  367 |       qry_descs = query_channel_lm.appearance.gpu_descriptors;
      |                                               ^~~~~~~~~~~~~~~
      |                                               descriptors
make[2]: *** [CMakeFiles/vtr_vision.dir/build.make:323: CMakeFiles/vtr_vision.dir/src/modules/matching/mel_matcher_module.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:337: CMakeFiles/vtr_vision.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
---
Failed   <<< vtr_vision [14.5s, exited with code 2]

Summary: 19 packages finished [24.9s]
  1 package failed: vtr_vision
  2 packages had stderr output: vtr_ui vtr_vision
  1 package not processed

**Comment by cheneyuwu** [comment]
Hi Rishabh,
I am not sure what's causing the error. 
could you share 1) hardware info (cpu, gpu) and 2) software versions - operating system, cuda, opencv, ros2
