### ISSUE TITLE
Hardware Configuration

### ISSUE THREAD

**Issue by SCOTA-YU** [utiasASRL/vtr3#139]
Can the VT&R3 algorithm be supported to run on Intel NUCs?

**Comment by cheneyuwu** [comment]
Hi - we don't have one so we cannot guarantee it is/will be supported.

**Comment by SCOTA-YU** [comment]
Ok thank you very much for your reply！
ok thank you very much for your reply

BIT
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "utiasASRL/vtr3"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月18日(星期一) 中午11:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [utiasASRL/vtr3] Hardware Configuration (Issue #139)





 
Hi - we don't have one so we cannot guarantee it is/will be supported.

**Comment by SCOTA-YU** [comment]
Hi, I would like to ask whether the GPU operation in the computer is occupied when using the VT&amp;R algorithm? Many thanks.


BIT
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "utiasASRL/vtr3"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月18日(星期一) 中午11:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [utiasASRL/vtr3] Hardware Configuration (Issue #139)





 
Hi - we don't have one so we cannot guarantee it is/will be supported.

**Comment by cheneyuwu** [comment]
Hi, yes we use GPU for feature matching, more details in the gpusurf library: https://github.com/utiasASRL/vtr3/tree/main/main/src/deps/gpusurf

**Comment by SCOTA-YU** [comment]
I'm very sorry for the delay in thanking you for your reply. We are preparing equipment to try to apply the VT&amp;R algorithm to our self-driving car. Hope to continue to get your help in the future, thank you again for your kind help!


I'm very sorry for the delay in thanking you for your reply. We are preparing equipment to try to apply the VT&amp;R algorithm to our self-driving car. Hope to continue to get your help in the future, thank you again for your kind help!

BIT
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "utiasASRL/vtr3"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月2日(星期二) 晚上7:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [utiasASRL/vtr3] Hardware Configuration (Issue #139)





 
Hi, yes we use GPU for feature matching, more details in the gpusurf library: https://github.com/utiasASRL/vtr3/tree/main/main/src/deps/gpusurf

**Comment by cheneyuwu** [comment]
no problem

**Comment by SCOTA-YU** [comment]
I learned that the VT&amp;R algorithm is actually running on a Lenovo laptop, I would like to know how your laptop is fixed on the robot, thank you very much!
I learned that the VT&amp;R algorithm is actually running on a Lenovo laptop, I would like to know how your laptop is fixed on the robot, thank you very much!

BIT
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "utiasASRL/vtr3"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月6日(星期六) 中午11:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [utiasASRL/vtr3] Hardware Configuration (Issue #139)





 
Closed #139 as completed.

**Comment by cheneyuwu** [comment]
We built a laptop holder and installed it on the robot, everytime we just place our laptops on the holder.

**Comment by SCOTA-YU** [comment]
If it is convenient, can you share a photo or video of the holder? thank you very much!


BIT
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "utiasASRL/vtr3"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月29日(星期一) 中午11:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [utiasASRL/vtr3] Hardware Configuration (Issue #139)





 
We built a laptop holder and installed it on the robot, everytime we just place our laptops on the holder.

**Comment by cheneyuwu** [comment]
Sure, I will take a photo next time at lab

**Comment by SCOTA-YU** [comment]
Thank you so much for your generous sharing!


BIT
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "utiasASRL/vtr3"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月30日(星期二) 凌晨3:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [utiasASRL/vtr3] Hardware Configuration (Issue #139)





 
Sure, I will take a photo next time at lab

**Comment by cheneyuwu** [comment]
Photo of the holder: https://drive.google.com/drive/folders/162Rj1aQPKhsA-q767iKdj7Xbes0QwdQW?usp=sharing
