### ISSUE TITLE
UI doesn't update in realtime like in the demo video

### ISSUE THREAD

**Issue by mcairlangga2** [utiasASRL/vtr3#173]
Hi, thank you for the great work. Recently, I've tried the demo as demonstrated in this link https://github.com/utiasASRL/vtr3/wiki/Lidar-Teach-and-Repeat 

I follow all the steps mentioned. The terminal is fine. However, the movement of robot and the path in GUI doesn't update in realtime as shown in the video i.e. I have to refresh my browser so that the GUI can show the path properly. 

Is there any suggestion to my problem?

Thanks!

**Comment by a-krawciw** [comment]
Hi thanks for your interest in the repository.

We have intermittently encountered this problem in some of our testing as well.
We notice it most often when VT&R is run on a different robot than this visualization.

Could you provide more information on your network and Docker configuration?

Thanks
