### ISSUE TITLE
Tried to load /home/docker/ASRL/vtr3/models/sample_model.pt

### ISSUE THREAD

**Issue by ccsmm78** [utiasASRL/vtr3#199]
We need pre-trained weight and its directory creation in the installation guide for new dockerfiles and code.
(https://github.com/utiasASRL/vtr3/wiki/Installation#building-vtr3)

**Comment by a-krawciw** [comment]
Hi there,

Sorry for missing that, that sample code is not really designed to be run. It's there to show how to build the file. 
I'm working on the update that will allow for easier selection of learned components or not.

**Comment by a-krawciw** [comment]
This has been fixed now.
